// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NoteFlier",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "NoteFlier",
            targets: ["AppModule"],
            bundleIdentifier: "to.nv0skar.NoteFlier",
            teamIdentifier: "5Y5W2JVDEP",
            displayVersion: "0.1",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/duraidabdul/LocalConsole.git", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/maustinstar/shiny.git", .branch("master")),
        .package(url: "https://github.com/omaralbeik/Drops.git", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/SwiftUI-Plus/Presentation.git", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/joogps/SlideOverCard.git", "2.0.0"..<"3.0.0"),
        .package(url: "https://github.com/stephencelis/SQLite.swift.git", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "LocalConsole", package: "localconsole"),
                .product(name: "Shiny", package: "shiny"),
                .product(name: "Drops", package: "drops"),
                .product(name: "Presentation", package: "presentation"),
                .product(name: "SlideOverCard", package: "slideovercard"),
                .product(name: "SQLite", package: "sqlite.swift")
            ],
            path: ".",
            exclude: ["README.md", "COPYING.txt"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
